// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqhsQkedfdBdET1jfw38FkvMEJVSDuHYY',
    appId: '1:80401209717:web:9b6e2edd50fb7f0f005b3c',
    messagingSenderId: '80401209717',
    projectId: 'guia-gamer',
    authDomain: 'guia-gamer.firebaseapp.com',
    storageBucket: 'guia-gamer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnePn2Bb8W1BQMT0VaAfUAKuDBSyatXBw',
    appId: '1:80401209717:android:228b472acc838fc6005b3c',
    messagingSenderId: '80401209717',
    projectId: 'guia-gamer',
    storageBucket: 'guia-gamer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvvduD5Q_perDdZdE27Aj9YcGO9uNytU8',
    appId: '1:80401209717:ios:501f35bd568d8986005b3c',
    messagingSenderId: '80401209717',
    projectId: 'guia-gamer',
    storageBucket: 'guia-gamer.appspot.com',
    iosClientId: '80401209717-bh2cb0smqi2k7h9aal0dlkjiluf04bsk.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
